### ISSUE TITLE
HPO 핸들러가있내요 ㅎㅎ?

### ISSUE THREAD

**Issue by 4pygmalion** [NewBornRustacean/rust_sandbox#1]
신기방기

**Comment by NewBornRustacean** [comment]
오 이 죽은 레포에 관심을ㅋㅋㅋㅋㅋ고맙읍니다ㅋㅋㅋ
 [fastobo](https://github.com/fastobo/fastobo) 가 러스트로 만든건데, 파이썬 바인딩이 좀 불편한 것 같아서 만들어보려다가ㅋㅋㅋㅋㅋ 빈 레포만 남았네요ㅠㅋㅋ

**Comment by 4pygmalion** [comment]
ㅋㅋ멋지십니다. 리포 구경 종종오겠습니다!
